feature_types: ['gene_expression']
#feature_types: ['gene_expression', 'chromatin_accessibility']

paths:
  compressed_atlas:
    "mouse": "./static/atlas_data/tabula_muris_senis.h5"
    "human": "./static/atlas_data/tabula_sapiens.h5"
    "lemur": "./static/atlas_data/tabula_microcebus.h5"
    "celegans": "./static/atlas_data/c_elegans.h5"
    "drerio": "./static/atlas_data/d_rerio.h5"

  # NOTE: this one is used for all species, depending on the column
  # FIXME: generalize to all species/pairs somehow
  gene_ids: "./static/atlas_data/mouse_gene_names.tsv"
  ortholog_genes: "./static/atlas_data/human_mouse_gene_orthologs.tsv"

  pathways:
    GO:
      "mouse": "./static/atlas_data/mouse_GO_tables.pkl"
    KEGG: "./static/atlas_data/kegg_pathway_dataframe.tsv"

pathways:
  KEGG:
    gene_set:
      "mouse": "KEGG_2019_Mouse"
      "human": "KEGG_2021_Human"
      "lemur": "KEGG_2021_Human"


defaults:
  tissue: "Lung"
  species: "mouse"
  celltype: "B"
  gene: "Actb"
  genestring: "Actc1,Actn2,Myl2,Myh7,Col1a1,Col2a1,Pdgfrb,Pecam1,Gja5,Vwf,Ptprc,Ms4a1,Gzma,Cd3d,Cd68,Epcam"

units:
  counts:
    long: "counts per ten thousand"


order:
  timepoint:
    "mouse": ['1m', '3m', '10m', '18m', '~19m', '21m', '24m', '30m']
    "human": ['31wk', '3yr', '31yr', '~60yr']
    "lemur": ["10", "11"]
    "celegans": ["2L"]
    "drerio": ["24hpf"]

  dataset:
    "mouse": ['TMS']
    "human": ['TS']
    "lemur": ['TMC']
    "celegans": ['TCE']

# celltype order is chosen at compression time elsewhere, otherwise this becomes a mess
